In [5]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
print(a[0])

[1 2 3 4]


In [12]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

TypeError: array() missing required argument 'object' (pos 0)

In [13]:
import numpy as np

a = np.array([1, 2, 3])

In [14]:
a

array([1, 2, 3])

In [15]:
#  you can easly create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
# Or an array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [18]:
# Or even an empty array
# The function empty creates an array whose initial content is random and depends on the states of the memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
# You can create an array with range of elements

print(np.arange(4))
print(np.arange(0,10,2))  # (start, stop, stop)


[0 1 2 3]
[0 2 4 6 8]


In [21]:
np.arange(2,29,5)


array([ 2,  7, 12, 17, 22, 27])

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [29]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [30]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [31]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                        
                        [[0, 1, 2, 3,],
                        [4, 5, 6, 7]],
                        
                        [[0, 1,2, 3],
                        [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [35]:
array_example.ndim

3

In [36]:
array_example.size

24

In [37]:
array_example.shape

(3, 2, 4)

In [40]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [42]:
arr_one.ndim

2

In [43]:
arr_one.shape

(1, 5)

In [44]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [45]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [46]:
a. reshape(6,1)
       

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [47]:
a= np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [48]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [50]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [51]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [52]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [53]:
# You can use np.expand to add an axis at index position 1 witth:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [54]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [56]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])


[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [57]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# You cab easly print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [59]:
five_up = (a >=5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [62]:
# You can select elements that divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [63]:
# you can select elemets that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])