In [12]:
conda install numpy

Note: you may need to restart the kernel to use updated packages.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\ria.dh\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.3.29  |       haa95532_1         122 KB
    certifi-2021.10.8          |   py39haa95532_2         152 KB
    conda-4.13.0               |   py39haa95532_0         923 KB
    openssl-1.1.1n             |       h2bbff1b_0         4.8 MB
    ------------------------------------------------------------
                                           Total:         6.0 MB


The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates                                  anaconda --> pkgs/main
  certifi                                          anaconda --> pkgs/main
  conda                   

In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
print(a[0])

[1 2 3 4]


In [ ]:
[[0., ,0., 0.],
[1., 1., 1.]]

In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [22]:
import numpy as np

a = np.array([1, 2, 3])

In [23]:
a

array([1, 2, 3])

In [24]:
# you can easly create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [25]:
# Or an array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [26]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of teh memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [31]:
 # You can create array with a range of elements
    
print(np.arange(4))
print(np.arange(0,10,2))  # (start, stop, step)
    

[0 1 2 3]
[0 2 4 6 8]


In [32]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
# Add, Remove and Sort

np.append()
np.delete()
np.sort()

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [36]:
# Hapus elemen

np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [37]:
# Sort

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [38]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Shape and size 

ndarray.ndim()  # memberi tahu jumlah axes atau dimensi array
ndarray.size()  # memberi tahu jumlah total elemen array
ndarray.shape()  # menampilakn tuple integer

In [48]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                         [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                         [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [49]:
array_example.ndim

3

In [50]:
array_example.size

24

In [51]:
array_example.shape

(3, 2, 4)

In [52]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [53]:
arr_one.ndim

2

In [54]:
arr_one.size

5

In [55]:
arr_one.shape

(1, 5)

In [ ]:
np.reshape()  # Memberi bentuk baru ke array tanpa mengubah data

In [57]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [58]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [59]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [60]:
np.newaxis
np.expand_dims

<function numpy.expand_dims(a, axis)>

In [61]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [62]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [63]:
# for a colum vector, You can inster an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)


(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [65]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape


(6, 1)

In [66]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [67]:
data = np. array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
# You can easily print all of the values in the array that are less than 5

print(a[a>5])

[ 6  7  8  9 10 11 12]


In [71]:
five_up = (a >= 5)

print(a[five_up])   # Or
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [72]:
# You can select elements that are visible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [73]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()


In [77]:
arr = np.array([a, 2, 3, 4, 5, 6, 7, 8, 9, 10])

C:\Users\ria.dh\AppData\Local\Temp\ipykernel_15672\1299125679.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([a, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [79]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8], dtype=object)

In [85]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [ ]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [86]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [88]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [94]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [95]:
# If you wanted to split the array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [96]:
a = np.array([[1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
# Using the copy method will make a complete copy of teh array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
# Basic array operations

a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [103]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [104]:
# You can sum the rows
b.sum(axis=0)

array([3, 3])

In [105]:
# You can sum the columns
b.sum(axis=1)

array([2, 4])

In [106]:
data = np.array([1, 2])
data

array([1, 2])

In [107]:
ones = np.ones(2)
ones

array([1., 1.])

In [108]:
data + ones

array([2., 3.])

In [109]:
data * data

array([1, 4])

In [110]:
data / data

array([1., 1.])

In [111]:
data * 2

array([2, 4])

In [ ]:
data.max()
data.min()
data.sum()

In [120]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [121]:
A.sum()

4.8595784

In [122]:
A.min()

0.05093587

In [123]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [124]:
A.max()

0.82485143

In [125]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [126]:
A.std()

0.21392120766089617

In [127]:
# Creating Matrices

np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.6821154 , 0.56162356],
       [0.80643581, 0.9844222 ],
       [0.90219198, 0.42861483]])

In [129]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.45224176 0.82521145]
 [0.61918306 0.37900793]
 [0.53430957 0.66759841]]


In [130]:
data =  np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [131]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [132]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [133]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [134]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [135]:
# Dot Product

a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[1, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 1  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [136]:
np.dot(a_1, a_2)

array([[ 52,  64],
       [115, 154]])

In [137]:
# Matrix Indexing

data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [138]:
# Matrix Aggregation

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [139]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [140]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [142]:
# Transposing and Reshaping

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [143]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [144]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [145]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [148]:
# N-Dimensional Array

ndarr = np.array([[[1, 2], [3, 4],
                  [5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [149]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [150]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [151]:
print(np.random.random((4,3,2)))

[[[0.08390936 0.9632755 ]
  [0.02263315 0.47146132]
  [0.21811595 0.80331142]]

 [[0.14542351 0.30490783]
  [0.26482509 0.04401052]
  [0.68995007 0.59065005]]

 [[0.27183084 0.2401657 ]
  [0.3840271  0.37364169]
  [0.20250046 0.75253526]]

 [[0.0754177  0.75758914]
  [0.12652368 0.0175504 ]
  [0.89249751 0.78101694]]]


In [152]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [154]:
# You can use flatten your array into a 1D array

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction)

In [ ]:
# Finish